# =========================================
#   Dataset decription
# =========================================  
# Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return 
# back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return 
# back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of 
# over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, 
# environmental and health issues. 
# 
# Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by
# these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration
# of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into
# a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important
# events in the city could be detected via monitoring these data.

# =========================================
#   Dataset characteristics
# =========================================  
# - instant: record index
# - dteday : date
# - season : season (1:springer, 2:summer, 3:fall, 4:winter)
# - yr : year (0: 2011, 1:2012)
# - mnth : month ( 1 to 12)
# - hr : hour (0 to 23)
# - holiday : weather day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
# - weekday : day of the week
# - workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
# + weathersit : 
# - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
# - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
# - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
# - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
# - temp : Normalized temperature in Celsius. The values are divided to 41 (max)
# - atemp: Normalized feeling temperature in Celsius. The values are divided to 50 (max)
# - hum: Normalized humidity. The values are divided to 100 (max)
# - windspeed: Normalized wind speed. The values are divided to 67 (max)
# - casual: count of casual users
# - registered: count of registered users
# - cnt: count of total rental bikes including both casual and registered



setwd("") #<-- change this to where you have downloaded the csv
data <- read.csv("C:/Users/Harshraj/Downloads/CA 1/hour.csv")

set.seed(17105137) # <-- put your student number here WITHOUT the x!! Leave off a starting zero if you have one
#e.g.: set.seed(62345678)
my_dataset <- data[order(runif(5000)), ]
my_dataset <- my_dataset[-1]

#output this if you want to use something other than R
write.csv(file="mydata.csv", my_dataset)

#Start Foundations
str(my_dataset)
my_dataset$season <- factor(my_dataset$season, levels = c(1,2,3,4), labels=c("springer", "summer", "fall", "winter"))
my_dataset$yr <- factor(my_dataset$yr, levels = c(0,1), labels=c("2011", "2012"))
my_dataset$holiday <- factor(my_dataset$holiday, levels = c(0,1), labels=c("workingday", "holiday"))
my_dataset$weekday <- factor(my_dataset$weekday, levels = c(0,1,2,3,4,5,6), labels=c("Mon","Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
my_dataset$workingday <- factor(my_dataset$workingday, levels = c(0,1), labels=c("workingday", "holiday"))
my_dataset$weathersit <- factor(my_dataset$weathersit, levels = c(1,2,3,4), labels=c("Clear", "Mist", "Light", "Heavy"))
#End Foundations
summary(my_dataset)
#2 Missing values
sapply(my_dataset,function(x) sum(is.na(x)))
#3-6
hist(my_dataset$temp)
summary(my_dataset$temp)
hist(my_dataset$atemp)
summary(my_dataset$atemp)
hist(my_dataset$hum)
summary(my_dataset$hum)
hist(my_dataset$windspeed)
summary(my_dataset$windspeed)
#7,8,9
plot(my_dataset$cnt, my_dataset$mnth, main = "Count vs. Month")
plot(my_dataset$cnt, my_dataset$hr, main = "Hourly Count")
plot(my_dataset$registered, my_dataset$weekday, main = "Registered Users of the week")
#doesn't look like it
install.packages("caret")
library(caret)
sample <- createDataPartition(my_dataset$cnt, p = .75, list = FALSE) 
train <- my_dataset[sample, ]
test <- my_dataset[-sample, ]


#I1
install.packages("C50")
library(C50)

cFifty <- C5.0(cnt ~., data=train, trials=100)


cFiftyPrediction <- predict(cFifty, newdata = test[, -2])
(cFiftyAccuracy <- 1- mean(cFiftyPrediction != test$cnt))
